version: 0.2
phases:
  install:
    commands:
      - echo "Skipping global install"
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - nnpx ng build --configuration=production
artifacts:
  base-directory: dist/my-angular-project
  files:
    - '**/*'